"""种子数据：由前端 mock 迁移而来（graph-data.ts / node-learning / path-planning / learning-history / ai-assistant / dashboard）。

说明：
- 节点 id 直接使用中文名，与前端图谱契约一致；
- 已修正前端 mock 中的拼写错误 Raserio → Rasterio；
- 学习记录的时间为“相对今天的天偏移”，种子脚本会转换成真实时间。
"""

from typing import Any

DOMAIN_ORDER: list[str] = [
    "遥感基础",
    "Python 数据处理",
    "遥感影像处理",
    "深度学习",
    "Transformer",
    "遥感大模型",
]

DEMO_EMAIL = "learner@remote-sensing.ai"
DEMO_PASSWORD = "stellar123"
DEMO_ACCOUNT_NO = "ACC001"
DEMO_NAME = "遥感学习者"

# ---------------------------------------------------------------- 知识图谱

# (id, name, domain, x, y, duration, seed_status)
KNOWLEDGE_NODES: list[dict[str, Any]] = [
    {
        "id": "遥感概论",
        "name": "遥感概论",
        "domain": "遥感基础",
        "x": 12,
        "y": 24,
        "duration": "30 分钟",
        "status": "mastered",
    },
    {
        "id": "电磁波与遥感",
        "name": "电磁波与遥感",
        "domain": "遥感基础",
        "x": 19,
        "y": 12,
        "duration": "35 分钟",
        "status": "mastered",
    },
    {
        "id": "遥感传感器",
        "name": "遥感传感器",
        "domain": "遥感基础",
        "x": 24,
        "y": 34,
        "duration": "40 分钟",
        "status": "mastered",
    },
    {
        "id": "遥感成像原理",
        "name": "遥感成像原理",
        "domain": "遥感基础",
        "x": 8,
        "y": 38,
        "duration": "45 分钟",
        "status": "mastered",
    },
    {
        "id": "Python 基础",
        "name": "Python 基础",
        "domain": "Python 数据处理",
        "x": 29,
        "y": 12,
        "duration": "25 分钟",
        "status": "mastered",
    },
    {
        "id": "NumPy",
        "name": "NumPy",
        "domain": "Python 数据处理",
        "x": 38,
        "y": 8,
        "duration": "35 分钟",
        "status": "mastered",
    },
    {
        "id": "Pandas",
        "name": "Pandas",
        "domain": "Python 数据处理",
        "x": 44,
        "y": 20,
        "duration": "40 分钟",
        "status": "mastered",
    },
    {
        "id": "GDAL",
        "name": "GDAL",
        "domain": "Python 数据处理",
        "x": 28,
        "y": 30,
        "duration": "50 分钟",
        "status": "mastered",
    },
    {
        "id": "Rasterio",
        "name": "Rasterio",
        "domain": "Python 数据处理",
        "x": 42,
        "y": 34,
        "duration": "45 分钟",
        "status": "mastered",
    },
    {
        "id": "影像预处理",
        "name": "影像预处理",
        "domain": "遥感影像处理",
        "x": 53,
        "y": 14,
        "duration": "35 分钟",
        "status": "mastered",
    },
    {
        "id": "几何校正",
        "name": "几何校正",
        "domain": "遥感影像处理",
        "x": 66,
        "y": 12,
        "duration": "45 分钟",
        "status": "mastered",
    },
    {
        "id": "辐射校正",
        "name": "辐射校正",
        "domain": "遥感影像处理",
        "x": 72,
        "y": 24,
        "duration": "40 分钟",
        "status": "mastered",
    },
    {
        "id": "图像增强",
        "name": "图像增强",
        "domain": "遥感影像处理",
        "x": 58,
        "y": 34,
        "duration": "30 分钟",
        "status": "mastered",
    },
    {
        "id": "特征提取",
        "name": "特征提取",
        "domain": "遥感影像处理",
        "x": 71,
        "y": 37,
        "duration": "35 分钟",
        "status": "mastered",
    },
    {
        "id": "神经网络基础",
        "name": "神经网络基础",
        "domain": "深度学习",
        "x": 18,
        "y": 66,
        "duration": "50 分钟",
        "status": "learning",
    },
    {
        "id": "CNN",
        "name": "CNN",
        "domain": "深度学习",
        "x": 28,
        "y": 78,
        "duration": "45 分钟",
        "status": "learning",
    },
    {
        "id": "目标检测",
        "name": "目标检测",
        "domain": "深度学习",
        "x": 34,
        "y": 63,
        "duration": "55 分钟",
        "status": "unlearned",
    },
    {
        "id": "图像分类",
        "name": "图像分类",
        "domain": "深度学习",
        "x": 20,
        "y": 82,
        "duration": "40 分钟",
        "status": "unlearned",
    },
    {
        "id": "语义分割",
        "name": "语义分割",
        "domain": "深度学习",
        "x": 32,
        "y": 89,
        "duration": "60 分钟",
        "status": "unlearned",
    },
    {
        "id": "Attention",
        "name": "Attention",
        "domain": "Transformer",
        "x": 50,
        "y": 59,
        "duration": "35 分钟",
        "status": "unlearned",
    },
    {
        "id": "Self-Attention",
        "name": "Self-Attention",
        "domain": "Transformer",
        "x": 58,
        "y": 72,
        "duration": "40 分钟",
        "status": "unlearned",
    },
    {
        "id": "Transformer",
        "name": "Transformer",
        "domain": "Transformer",
        "x": 64,
        "y": 61,
        "duration": "45 分钟",
        "status": "unlearned",
    },
    {
        "id": "Vision Transformer",
        "name": "Vision Transformer",
        "domain": "Transformer",
        "x": 51,
        "y": 82,
        "duration": "50 分钟",
        "status": "unlearned",
    },
    {
        "id": "Swin Transformer",
        "name": "Swin Transformer",
        "domain": "Transformer",
        "x": 68,
        "y": 83,
        "duration": "55 分钟",
        "status": "unlearned",
    },
    {
        "id": "多模态模型",
        "name": "多模态模型",
        "domain": "遥感大模型",
        "x": 78,
        "y": 48,
        "duration": "60 分钟",
        "status": "unlearned",
    },
    {
        "id": "遥感视觉语言模型",
        "name": "遥感视觉语言模型",
        "domain": "遥感大模型",
        "x": 89,
        "y": 58,
        "duration": "70 分钟",
        "status": "unlearned",
    },
    {
        "id": "遥感基础模型",
        "name": "遥感基础模型",
        "domain": "遥感大模型",
        "x": 82,
        "y": 70,
        "duration": "65 分钟",
        "status": "unlearned",
    },
    {
        "id": "遥感大模型应用",
        "name": "遥感大模型应用",
        "domain": "遥感大模型",
        "x": 92,
        "y": 74,
        "duration": "50 分钟",
        "status": "unlearned",
    },
]

KNOWLEDGE_EDGES: list[tuple[str, str]] = [
    ("遥感概论", "电磁波与遥感"),
    ("电磁波与遥感", "遥感传感器"),
    ("遥感概论", "遥感成像原理"),
    ("Python 基础", "NumPy"),
    ("Python 基础", "Pandas"),
    ("NumPy", "GDAL"),
    ("GDAL", "Rasterio"),
    ("遥感成像原理", "影像预处理"),
    ("影像预处理", "几何校正"),
    ("几何校正", "图像增强"),
    ("图像增强", "特征提取"),
    ("遥感成像原理", "神经网络基础"),
    ("神经网络基础", "CNN"),
    ("CNN", "目标检测"),
    ("CNN", "图像分类"),
    ("目标检测", "语义分割"),
    ("神经网络基础", "Attention"),
    ("Attention", "Self-Attention"),
    ("Self-Attention", "Transformer"),
    ("Transformer", "Vision Transformer"),
    ("Vision Transformer", "Swin Transformer"),
    ("Transformer", "多模态模型"),
    ("多模态模型", "遥感视觉语言模型"),
    ("Transformer", "遥感基础模型"),
    ("遥感视觉语言模型", "遥感大模型应用"),
]

# 节点详情（description, progress）：优先于按状态推导的默认值
NODE_DETAILS: dict[str, tuple[str, int]] = {
    "Transformer": ("Transformer 是基于注意力机制的深度学习架构。", 0),
    "Attention": ("Attention 机制使模型能够关注关键信息并提升表达能力。", 0),
    "Self-Attention": ("Self-Attention 能让模型在序列中自动建立上下文关系。", 0),
    "CNN": ("CNN 通过卷积核提取局部特征，适合图像分析任务。", 45),
    "神经网络基础": ("神经网络基础涵盖感知机、反向传播和多层结构。", 55),
    "遥感大模型应用": ("遥感大模型应用将基础模型迁移到地表分析和业务场景。", 0),
}

# ---------------------------------------------------------------- 节点学习

# completed: 是否已完成；progress: 当前进度（0-100）
LEARNING_NODES: list[dict[str, Any]] = [
    {
        "id": "遥感概论",
        "group_name": "遥感影像处理",
        "title": "遥感概论",
        "breadcrumb": "遥感基础 / 遥感概论",
        "summary": "建立对遥感技术体系、应用场景与基本概念的整体认识。",
        "duration": "25 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["理解遥感的基本定义与组成", "了解遥感的主要应用领域", "建立遥感技术体系框架"],
        "methods": ["概念学习", "应用案例观察", "知识框架梳理"],
        "concept": "遥感是在不接触目标的情况下，通过传感器获取地表信息并进行分析的技术体系。",
        "case_title": "案例：城市热岛遥感监测",
        "case_summary": "利用热红外遥感数据反演城市地表温度，分析热岛效应的空间分布。",
        "explanation": "简单来说，遥感就是“从远处感知”，用卫星或飞机上的传感器代替人眼去观测地球。",
    },
    {
        "id": "电磁波与遥感",
        "group_name": "遥感影像处理",
        "title": "电磁波与遥感",
        "breadcrumb": "遥感基础 / 电磁波与遥感",
        "summary": "理解电磁波谱、反射与辐射特性，是理解遥感成像的物理基础。",
        "duration": "35 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["掌握电磁波谱基本分段", "理解地物反射与辐射特性", "建立波段与地物关系"],
        "methods": ["波谱分析", "反射率曲线解读", "波段组合观察"],
        "concept": "不同地物在不同波段表现出不同的反射和辐射特性，这是遥感识别地物的物理依据。",
        "case_title": "案例：植被红边效应",
        "case_summary": "利用近红外波段的强反射特性区分健康植被与其它地物。",
        "explanation": "简单来说，每种地物都有自己独特的“光谱指纹”，遥感就是通过读取这些指纹来识别地物。",
    },
    {
        "id": "遥感成像原理",
        "group_name": "遥感影像处理",
        "title": "遥感成像原理",
        "breadcrumb": "遥感基础 / 遥感成像原理",
        "summary": "理解传感器如何将地物辐射转换为可分析的影像数据。",
        "duration": "45 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["理解成像的物理过程", "掌握空间、光谱、时间分辨率概念", "理解影像数据的基本形式"],
        "methods": ["成像链路梳理", "分辨率参数对比", "影像样例分析"],
        "concept": "遥感成像是传感器接收地物辐射能量，并将其转换为数字影像的过程，分辨率决定影像的信息能力。",
        "case_title": "案例：多分辨率影像对比",
        "case_summary": "对比不同分辨率影像在城市建设区识别中的表现差异。",
        "explanation": "简单来说，成像原理回答的是“照片是怎么拍出来、又是怎么变成数字的”。",
    },
    {
        "id": "遥感传感器",
        "group_name": "遥感影像处理",
        "title": "遥感传感器",
        "breadcrumb": "遥感基础 / 遥感传感器",
        "summary": "认识光学、热红外与雷达等主流传感器及其适用场景。",
        "duration": "40 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["了解主要传感器类型", "掌握传感器参数含义", "理解传感器选择依据"],
        "methods": ["参数对比", "任务匹配分析", "典型数据认识"],
        "concept": "不同传感器在波段范围、分辨率与观测方式上各有特点，需要根据任务选择合适的传感器。",
        "case_title": "案例：光学与雷达影像对比",
        "case_summary": "对比光学影像与 SAR 影像在阴雨天气下的观测能力差异。",
        "explanation": "简单来说，传感器就是遥感的“眼睛”，不同的眼睛适合看不同的东西。",
    },
    {
        "id": "Python 基础",
        "group_name": "遥感影像处理",
        "title": "Python 基础",
        "breadcrumb": "Python 数据处理 / Python 基础",
        "summary": "掌握 Python 基本语法与开发环境，为遥感数据处理打基础。",
        "duration": "25 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["掌握基本语法与数据结构", "熟悉 Jupyter 环境", "能编写简单数据处理脚本"],
        "methods": ["语法练习", "小脚本编写", "调试技巧"],
        "concept": "Python 是遥感数据处理的主流语言，语法简洁，生态丰富。",
        "case_title": "案例：批量重命名影像文件",
        "case_summary": "编写脚本批量整理目录中的影像文件，体验自动化处理。",
        "explanation": "简单来说，Python 是处理遥感数据的工具，先把基本语法练熟。",
    },
    {
        "id": "NumPy",
        "group_name": "遥感影像处理",
        "title": "NumPy",
        "breadcrumb": "Python 数据处理 / NumPy",
        "summary": "用数组化思维高效处理遥感影像的像元数据。",
        "duration": "35 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["掌握 ndarray 基本操作", "理解向量化计算", "掌握切片与广播"],
        "methods": ["数组操作练习", "向量化改写", "性能对比"],
        "concept": "遥感影像本质上是多维数组，NumPy 提供了高效的数组运算能力。",
        "case_title": "案例：波段运算增强植被",
        "case_summary": "通过波段差值与归一化运算突出植被信息。",
        "explanation": "简单来说，NumPy 让你像操作表格一样操作整幅影像，而不是一个个像元地处理。",
    },
    {
        "id": "Pandas",
        "group_name": "遥感影像处理",
        "title": "Pandas",
        "breadcrumb": "Python 数据处理 / Pandas",
        "summary": "用表格化方式清洗、统计与分析遥感采样数据。",
        "duration": "40 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["掌握 DataFrame 基本操作", "掌握缺失值与重采样处理", "能完成统计汇总"],
        "methods": ["数据清洗", "分组统计", "缺失值处理"],
        "concept": "Pandas 适合处理属性表、采样点与统计数据，与 NumPy 互补。",
        "case_title": "案例：采样点数据清洗",
        "case_summary": "对野外采样点数据进行缺失值处理与统计汇总。",
        "explanation": "简单来说，Pandas 处理的是“表格数据”，比如采样点的属性信息。",
    },
    {
        "id": "GDAL",
        "group_name": "遥感影像处理",
        "title": "GDAL",
        "breadcrumb": "Python 数据处理 / GDAL",
        "summary": "读写常见栅格格式，打通影像处理与数据落地的链路。",
        "duration": "50 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["掌握栅格数据读取与写出", "理解地理参考信息", "能进行格式转换"],
        "methods": ["栅格读写", "元数据查看", "格式转换"],
        "concept": "GDAL 是地理空间数据处理的底层库，支持几乎全部遥感数据格式。",
        "case_title": "案例：GeoTIFF 格式转换",
        "case_summary": "将影像转换为 GeoTIFF 并保留地理参考信息。",
        "explanation": "简单来说，GDAL 是遥感数据世界的“通用读卡器”。",
    },
    {
        "id": "影像预处理",
        "group_name": "遥感影像处理",
        "title": "影像预处理",
        "breadcrumb": "遥感影像处理 / 影像预处理",
        "summary": "理解预处理在遥感分析流程中的位置与作用。",
        "duration": "35 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["了解预处理流程", "理解各步骤的目的", "能规划预处理方案"],
        "methods": ["流程拆解", "案例走查", "问题诊断"],
        "concept": "预处理为后续分析提供质量可靠的数据输入，包括校正、去噪与配准等步骤。",
        "case_title": "案例：影像质量诊断",
        "case_summary": "通过检查云量、条带与几何偏差判断影像是否可直接使用。",
        "explanation": "简单来说，预处理就是“把数据洗干净再下锅”。",
    },
    {
        "id": "几何校正",
        "group_name": "遥感影像处理",
        "title": "几何校正",
        "breadcrumb": "遥感影像处理 / 几何校正",
        "summary": "消除影像几何变形，让像素位置对应真实地理坐标。",
        "duration": "45 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["理解几何变形来源", "掌握控制点校正思路", "理解重采样方法"],
        "methods": ["控制点选取", "多项式校正", "重采样"],
        "concept": "几何校正通过建立影像坐标与地理坐标的映射关系，消除地形与传感器姿态带来的变形。",
        "case_title": "案例：正射校正实验",
        "case_summary": "利用控制点对山区影像进行校正，减小地形引起的位移。",
        "explanation": "简单来说，几何校正就是让影像上的位置“对得上地图”。",
    },
    {
        "id": "辐射校正",
        "group_name": "遥感影像处理",
        "title": "辐射校正",
        "breadcrumb": "遥感影像处理 / 辐射校正",
        "summary": "消除传感器与大气影响，获取真实的地表反射信息。",
        "duration": "40 分钟",
        "completed": True,
        "progress": 100,
        "objectives": ["理解辐射误差来源", "掌握辐射定标流程", "了解大气校正的作用"],
        "methods": ["辐射定标", "大气校正", "光谱对比"],
        "concept": "辐射校正将影像灰度值转换为地表反射率，使不同时间与传感器数据可比。",
        "case_title": "案例：大气校正前后对比",
        "case_summary": "对比校正前后的植被光谱曲线，观察大气散射的去除效果。",
        "explanation": "简单来说，辐射校正就是还原地物“真实的亮度”。",
    },
    {
        "id": "图像增强",
        "group_name": "遥感影像处理",
        "title": "图像增强",
        "breadcrumb": "遥感影像处理 / 图像增强",
        "summary": "提升遥感影像的视觉质量与特征表达能力，使后续分类、目标检测和特征提取可以从更清晰的输入中受益。",
        "duration": "20 分钟",
        "completed": False,
        "progress": 42,
        "objectives": [
            "理解遥感影像增强的基本概念",
            "掌握常见影像增强方法",
            "理解增强方法对后续特征提取的影响",
        ],
        "methods": ["对比度增强", "直方图均衡化", "空间域增强", "锐化"],
        "concept": "遥感影像增强是通过一定的图像处理方法改善影像视觉效果，突出目标地物和重要信息，为后续分类、目标检测和特征提取提供更好的输入。",
        "case_title": "案例：城市遥感影像增强",
        "case_summary": "利用增强处理提升城市建筑、道路和植被区域的可分辨度，改善后续地物识别和变化检测任务的输入质量。",
        "explanation": "简单来说，图像增强就是让模型更容易“看清”图中的关键内容，尤其是在对比度不足、光照不稳定或噪声较多的遥感影像中。",
    },
    {
        "id": "特征提取",
        "group_name": "遥感影像处理",
        "title": "特征提取",
        "breadcrumb": "遥感影像处理 / 特征提取",
        "summary": "从遥感影像中提取纹理、边缘、形状和光谱特征，帮助后续分类和目标识别更稳定。",
        "duration": "25 分钟",
        "completed": False,
        "progress": 28,
        "objectives": ["理解纹理和边缘特征", "掌握特征提取思路", "理解与增强的协同关系"],
        "methods": ["边缘检测", "纹理分析", "光谱特征提取", "形状描述"],
        "concept": "特征提取的关键是从原始图像中抽取出对任务更有价值的信息，使模型更容易从复杂背景中识别目标。",
        "case_title": "案例：道路与建筑物提取",
        "case_summary": "通过综合利用边缘、纹理和空间结构信息，提升建筑物和道路等目标的分离能力。",
        "explanation": "简单来说，特征提取相当于把原始图像“压缩成更有用的信号”，帮助后续模型更快地判断目标类型。",
    },
    {
        "id": "Rasterio",
        "group_name": "遥感影像处理",
        "title": "Rasterio",
        "breadcrumb": "Python 数据处理 / Rasterio",
        "summary": "用 Python 原生方式高效读写遥感栅格数据并处理地理元信息。",
        "duration": "30 分钟",
        "completed": False,
        "progress": 0,
        "objectives": ["掌握 Rasterio 读写流程", "理解窗口读取与重采样", "能与 NumPy 数组协同处理"],
        "methods": ["栅格读取", "窗口裁剪", "重采样", "数组协同"],
        "concept": "Rasterio 基于 GDAL 提供了更符合 Python 习惯的栅格读写接口，适合构建自动化处理管线。",
        "case_title": "案例：大区域影像窗口读取",
        "case_summary": "利用窗口读取方式处理超大影像，避免一次性载入内存。",
        "explanation": "简单来说，Rasterio 让“读影像”变得像读普通文件一样自然。",
    },
    {
        "id": "CNN",
        "group_name": "遥感影像处理",
        "title": "CNN",
        "breadcrumb": "深度学习 / CNN",
        "summary": "理解卷积神经网络如何从遥感影像中自动学习空间特征。",
        "duration": "30 分钟",
        "completed": False,
        "progress": 0,
        "objectives": ["理解卷积与池化操作", "掌握经典网络结构", "了解在遥感分类中的应用"],
        "methods": ["卷积运算", "池化", "特征图可视化", "迁移学习"],
        "concept": "CNN 通过局部感受野和权值共享高效提取图像空间特征，是遥感影像分类与检测的基础模型。",
        "case_title": "案例：CNN 土地覆盖分类",
        "case_summary": "使用卷积网络对多光谱影像进行土地覆盖类型分类。",
        "explanation": "简单来说，CNN 就像一个自动学会“看图”的过滤器组，从简单边缘一路组合出复杂地物特征。",
    },
    {
        "id": "目标检测",
        "group_name": "遥感影像处理",
        "title": "目标检测",
        "breadcrumb": "深度学习 / 目标检测",
        "summary": "在大范围影像中定位并识别目标对象，例如车辆、建筑物和水体。",
        "duration": "30 分钟",
        "completed": False,
        "progress": 18,
        "objectives": ["理解检测框与类别预测", "掌握遥感场景中的目标定位", "了解检测任务的输出结构"],
        "methods": ["候选区域", "边界回归", "分类与定位", "多尺度检测"],
        "concept": "目标检测不仅需要识别“是什么”，还需要判断“在哪里”，在遥感任务中这对大面积场景尤为重要。",
        "case_title": "案例：港口船舶检测",
        "case_summary": "利用遥感影像中的多尺度特征，对港口和航道中的船舶目标进行定位和识别。",
        "explanation": "简单来说，目标检测解决的是“找出对象并标出它的位置”，这比单纯分类更适合大范围遥感场景。",
    },
    {
        "id": "Transformer",
        "group_name": "遥感影像处理",
        "title": "Transformer",
        "breadcrumb": "深度学习 / Transformer",
        "summary": "Transformer 利用注意力机制建立全局关系，适合分析遥感影像中的长距离空间关联。",
        "duration": "35 分钟",
        "completed": False,
        "progress": 12,
        "objectives": ["理解 Self-Attention 原理", "掌握全局特征建模", "理解其在遥感任务中的适配"],
        "methods": ["自注意力", "多头注意力", "位置编码", "残差连接"],
        "concept": "Transformer 通过学习不同区域之间的关联关系，构建全局语义表达，从而有效捕获遥感影像中的上下文信息。",
        "case_title": "案例：土地覆盖分类",
        "case_summary": "使用 Transformer 对多光谱影像中的区域交互关系进行建模，提高不同地物间的区分能力。",
        "explanation": "简单来说，Transformer 相当于让模型在图像中“看全局”，而不只是关注局部细节。",
    },
    {
        "id": "遥感大模型",
        "group_name": "遥感影像处理",
        "title": "遥感大模型",
        "breadcrumb": "大模型与智能应用 / 遥感大模型",
        "summary": "大模型能够在大规模遥感数据上学习通用表征，并应用于分类、检测和场景理解。",
        "duration": "40 分钟",
        "completed": False,
        "progress": 6,
        "objectives": ["理解大模型迁移思路", "了解遥感通用表示", "建立模型落地视角"],
        "methods": ["预训练模型", "微调", "迁移学习", "多模态对齐"],
        "concept": "遥感大模型使用大规模数据学习基础表征，可以在多种任务上做迁移和增强，降低单任务训练门槛。",
        "case_title": "案例：遥感大模型应用",
        "case_summary": "在土地覆盖、灾害识别和基础设施检测中，利用预训练大模型提升泛化能力与任务适配效率。",
        "explanation": "简单来说，大模型帮助系统从海量遥感数据中学到“通用认知”，再将其迁移到具体任务上。",
    },
]

# ---------------------------------------------------------------- 学习路径

PATH_STAGES: list[dict[str, Any]] = [
    {
        "key": "foundation",
        "title": "遥感基础巩固",
        "summary": "强化电磁波、成像原理与传感器认知",
        "duration": "3 周",
        "difficulty": "基础",
        "focus": "概念复盘 + 实战演练",
        "objective": "建立稳定的遥感底层认知",
        "status": "done",
        "learning_goal": "掌握遥感的基本观测原理和传感器特性",
        "recommended_content": ["电磁波基础复盘", "传感器特征梳理", "遥感成像案例实战"],
        "prerequisites": ["无"],
        "completion": 82,
        "estimated_time": "3 周 / 7 小时",
        "detail": "通过概念复盘与案例练习，建立遥感观测原理的整体认知，为后续数据处理和建模任务做好准备。",
    },
    {
        "key": "python",
        "title": "Python 数据处理",
        "summary": "形成高效的可视化与数据清洗习惯",
        "duration": "2 周",
        "difficulty": "中等",
        "focus": "NumPy / Pandas / GDAL",
        "objective": "掌握遥感数据处理主流程",
        "status": "active",
        "learning_goal": "能够完成影像读取、清洗、可视化和统计分析任务",
        "recommended_content": ["NumPy 向量化处理", "Pandas 数据清洗", "GDAL 影像读取与栅格转换"],
        "prerequisites": ["Python 基础", "遥感概论"],
        "completion": 58,
        "estimated_time": "2 周 / 6 小时",
        "detail": "当前阶段重点在于把遥感数据从“原始文件”转化成可分析的结构化数据，并建立稳定的处理工作流。",
    },
    {
        "key": "image-processing",
        "title": "影像处理与特征提取",
        "summary": "学习几何校正、辐射校正和图像增强",
        "duration": "3 周",
        "difficulty": "中等",
        "focus": "增强 / 校正 / 提取",
        "objective": "打通从原始影像到分析结果的链路",
        "status": "locked",
        "learning_goal": "掌握辐射校正、几何校正和特征增强方法",
        "recommended_content": ["几何校正案例", "辐射校正评估", "纹理与边缘特征提取"],
        "prerequisites": ["Python 数据处理", "遥感成像原理"],
        "completion": 24,
        "estimated_time": "3 周 / 9 小时",
        "detail": "这一阶段将把原始影像处理成适合后续分析的质量产品，提升对地表特征的识别能力。",
    },
    {
        "key": "dl",
        "title": "深度学习建模",
        "summary": "掌握 CNN、目标检测与语义分割思路",
        "duration": "4 周",
        "difficulty": "进阶",
        "focus": "卷积网络 / 目标检测",
        "objective": "对遥感任务建立模型判读能力",
        "status": "locked",
        "learning_goal": "形成从数据到模型的完整遥感判读训练流程",
        "recommended_content": ["CNN 基础网络", "目标检测训练", "语义分割评估"],
        "prerequisites": ["Python 数据处理", "影像处理与特征提取"],
        "completion": 12,
        "estimated_time": "4 周 / 12 小时",
        "detail": "在掌握影像处理后，继续向深度学习建模推进，建立从特征工程到模型判读的能力闭环。",
    },
    {
        "key": "llm",
        "title": "大模型与智能应用",
        "summary": "接入遥感大模型与跨模态推理能力",
        "duration": "3 周",
        "difficulty": "高级",
        "focus": "微调 / 迁移 / 推理",
        "objective": "形成业务落地与智能分析闭环",
        "status": "locked",
        "learning_goal": "能够使用大模型完成遥感任务的迁移和推理增强",
        "recommended_content": ["大模型基础理解", "遥感任务迁移", "跨模态推理应用"],
        "prerequisites": ["深度学习建模", "Python 数据处理"],
        "completion": 8,
        "estimated_time": "3 周 / 10 小时",
        "detail": "最终阶段侧重将已有技能延伸到大模型能力上，强化遥感智能应用与业务生成能力。",
    },
]

# 学习节点 → 路径阶段的映射（用于按学习进度重算阶段完成度）
STAGE_NODE_MAP: dict[str, list[str]] = {
    "foundation": ["遥感概论", "电磁波与遥感", "遥感成像原理", "遥感传感器"],
    "python": ["Python 基础", "NumPy", "Pandas", "GDAL", "Rasterio"],
    "image-processing": ["影像预处理", "几何校正", "辐射校正", "图像增强", "特征提取"],
    "dl": ["CNN", "目标检测"],
    "llm": ["Transformer", "遥感大模型"],
}

PATH_ANALYSIS_VARIANTS: list[dict[str, str]] = [
    {
        "title": "AI 学习路径分析",
        "subtitle": "根据你近期进度，适合继续推进 Python 数据处理模块，保持 2 周冲刺节奏。",
        "badge": "专属推荐",
        "momentum": "+8% 专项提升",
        "next_action": "下一步：完成 Rasterio + 影像可视化案例",
    },
    {
        "title": "当前学习节奏建议",
        "subtitle": "你已完成基础概念复盘，当前最关键的是把数据处理能力转化为实战案例。",
        "badge": "效率优先",
        "momentum": "+12% 产出速度",
        "next_action": "下一步：用 3 个真实任务强化 GDAL 与 Pandas 应用",
    },
]

# ---------------------------------------------------------------- 学习记录

# 最近学习会话（day_offset: 0=今天, 1=昨天, 2=前天）
RECENT_SESSIONS: list[dict[str, Any]] = [
    {
        "title": "图像增强复盘",
        "category": "影像处理",
        "duration_minutes": 42,
        "score": 92,
        "day_offset": 0,
        "time": "08:30",
        "summary": "回顾了直方图均衡化与 CLAHE 的适用场景，并完成 1 个案例复述。",
    },
    {
        "title": "Pandas 数据清洗",
        "category": "数据处理",
        "duration_minutes": 31,
        "score": 88,
        "day_offset": 1,
        "time": "19:15",
        "summary": "完成重采样、缺失值处理和多波段表格清洗，形成稳定实践模板。",
    },
    {
        "title": "遥感目标检测",
        "category": "深度学习",
        "duration_minutes": 57,
        "score": 84,
        "day_offset": 2,
        "time": "20:10",
        "summary": "复习边界框回归与 IoU 评估，进一步理解检测任务中分辨率的影响。",
    },
]

# 时间线事件（is_timeline=True 的记录）
TIMELINE_ENTRIES: list[dict[str, Any]] = [
    {
        "title": "完成“图像增强”单元测试",
        "tag": "已完成",
        "day_offset": 0,
        "time": "08:30",
        "summary": "完成 1 次单元知识检测，准确率达到 92%。",
    },
    {
        "title": "新增 Python 数据清洗案例",
        "tag": "学习记录",
        "day_offset": 1,
        "time": "19:15",
        "summary": "在 GDAL + Pandas 流程中添加了 2 个真实影像处理案例。",
    },
    {
        "title": "学习路径调整：推进 Transformer",
        "tag": "路径优化",
        "day_offset": 3,
        "time": None,
        "summary": "结合最近掌握度评分，调整下一阶段优先顺序至 Transformer 与目标检测。",
    },
    {
        "title": "沉淀 3 个关键概念卡片",
        "tag": "知识整理",
        "day_offset": 7,
        "time": None,
        "summary": "补充了“对比度增强”“边缘特征”“局部上下文”的学习卡片。",
    },
]

# 90 天历史记录生成池：(标题, 分类, 摘要)
RECORD_POOL: list[tuple[str, str, str]] = [
    ("图像增强练习", "影像处理", "练习对比度拉伸与直方图均衡化，观察增强前后差异。"),
    ("GDAL 栅格读写", "数据处理", "完成栅格读取、波段提取与格式转换练习。"),
    ("NumPy 波段运算", "数据处理", "使用数组运算实现 NDVI 与波段归一化。"),
    ("几何校正案例", "影像处理", "选取控制点完成一次多项式校正实验。"),
    ("辐射校正实验", "影像处理", "对比辐射定标前后影像亮度分布变化。"),
    ("CNN 基础复习", "深度学习", "复习卷积、池化与感受野等核心概念。"),
    ("Transformer 原理学习", "深度学习", "学习 Self-Attention 的计算流程与意义。"),
    ("知识问答：Attention 机制", "知识问答", "通过 AI 助手梳理 Attention 与 CNN 的差异。"),
    ("学习路径回顾", "路径复习", "回顾当前学习路径并标记下一阶段重点。"),
    ("遥感概论复习", "基础概念", "梳理遥感系统组成与典型应用场景。"),
    ("特征提取练习", "影像处理", "提取边缘与纹理特征并观察分类效果变化。"),
    ("多光谱影像分析", "影像处理", "分析多光谱波段组合对地物区分的影响。"),
    ("模型评估指标学习", "深度学习", "学习精确率、召回率与 mAP 的含义。"),
    ("学习笔记整理", "知识整理", "整理本周知识点并沉淀为概念卡片。"),
    ("Pandas 统计分析", "数据处理", "完成采样点属性数据的统计与可视化。"),
]

# ---------------------------------------------------------------- AI 对话

CONVERSATIONS: list[dict[str, Any]] = [
    {
        "id": "image-enhance",
        "title": "遥感影像增强怎么学习？",
        "category": "知识问答",
        "messages": [
            {
                "role": "assistant",
                "content": "你好，我是你的遥感学习助手。我可以帮助你：\n• 解释遥感专业知识\n• 制定学习路径\n• 分析知识薄弱点\n• 解答代码问题\n• 总结学习内容\n你可以直接问我。",
            },
            {"role": "user", "content": "什么是直方图均衡化？"},
            {
                "role": "assistant",
                "content": "直方图均衡化是一种常见的图像增强方法，它通过重新分配图像像素的灰度分布，提高图像整体的对比度。\n在遥感影像处理中，它可以帮助突出地物之间的差异，方便后续的特征提取和分类。\n结合你当前正在学习的图像增强，建议你继续了解 CLAHE 和局部对比度增强。",
            },
        ],
    },
    {
        "id": "transformer-guide",
        "title": "Transformer 学习路线",
        "category": "学习规划",
        "messages": [
            {
                "role": "assistant",
                "content": "Transformer 的学习路线可以分成 4 个阶段：基础概念 → 结构理解 → 遥感案例 → 实践训练。你现在已经具备 CNN 和图像处理基础，下一步最适合直接学习 Self-Attention。",
            }
        ],
    },
    {
        "id": "cnn-vs-transformer",
        "title": "CNN 和 Transformer 的区别",
        "category": "知识问答",
        "messages": [
            {
                "role": "assistant",
                "content": "CNN 更擅长提取局部空间特征，而 Transformer 更擅长建模全局关系。遥感任务中，前者适合细粒度局部识别，后者适合理解大范围上下文。",
            }
        ],
    },
    {
        "id": "llm-intro",
        "title": "遥感大模型入门",
        "category": "学习规划",
        "messages": [
            {
                "role": "assistant",
                "content": "想学遥感大模型，建议从“预训练基础 + 任务迁移 + 实验落地”三步入手。先建立通用模型理解，再结合遥感数据做微调和评估。",
            }
        ],
    },
    {
        "id": "python-remote",
        "title": "Python 遥感数据处理",
        "category": "知识总结",
        "messages": [
            {
                "role": "assistant",
                "content": "Python 在遥感数据处理中主要负责读取、清洗、可视化和统计分析。NumPy 和 Pandas 负责数值与表格处理，GDAL 负责栅格数据读取与转换。",
            }
        ],
    },
]
